package com.tikkie.model;

import com.tikkie.converter.InstantCreatedConverter;
import com.tikkie.util.Constants;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.Instant;

/**
 * @author Mohamed Ibrahim
 * @created Tuesday 25 Oct 2022
 */
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDbBean
public class Person {

    private String id;

    private String fullName;

    private String firstname;

    private String lastname;

    private String phoneNumber;

    private Address address;

    private Instant created;

    @DynamoDbPartitionKey
    @DynamoDbSecondarySortKey(indexNames = Constants.FULL_NAME_GLOBAL_SECONDARY_INDEX)
    public String getId() {

        return id;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("fullName")
    @DynamoDbSecondaryPartitionKey(indexNames = {Constants.FULL_NAME_GLOBAL_SECONDARY_INDEX})
    public String getFullName() {

        return fullName;
    }

    @DynamoDbAttribute("firstname")
    public String getFirstname() {

        return firstname;
    }

    @DynamoDbAttribute("lastname")
    public String getLastname() {

        return lastname;
    }

    @DynamoDbAttribute("phoneNumber")
    public String getPhoneNumber() {

        return phoneNumber;
    }

    @DynamoDbAttribute("address")
    public Address getAddress() {

        return address;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbConvertedBy(InstantCreatedConverter.class)
    public Instant getCreated() {

        return created;
    }

}
